### ISSUE TITLE
Install with ta-lib via homebrew

### ISSUE THREAD

**Issue by gamafranco** [rivella50/talib-ruby#3]
Hi,

i would like to know if it's easy to allow the gem to install with ta-lib from homebrew, instead of Macports.

Thanks.

**Comment by rivella50** [comment]
Hi,

in theory it should work, probably Homebrew will just install ta-lib in a different directory, therefore the 2 directories you have to name for headers and libs can be different when you install the gem:

sudo env ARCHFLAGS="-arch PLATFORM" gem install talib_ruby -- --with-talib-include=ABSOLUTE_PATH_TO_TALIB_HEADERS  --with-talib-lib=ABSOLUTE_PATH_TO_TALIB_LIBS

Please try it and let me know if it worked.
Thank you.

**Comment by gamafranco** [comment]
Hi,

It worked. Thanks.

i wonder what are the alternatives to make the instalation of talib_ruby without params. This would enable to install it with bundler out of the box.

Thanks,
Tiago Franco
gama.franco@gmail.com
http://imaginarycloud.com

**Comment by rivella50** [comment]
Hi Tiago,

the problem is that i do not know for sure where to look for the header/lib dirs on a certain system when installing the gem.
If you have an idea let it hear :-)
Of course you can also fork the source to implement a better solution to what i currently offer.

Bests
Valentin
